"""Add WordPress fields to APIKey

Revision ID: 3a87876886ac
Revises: b5efd0b4eea0
Create Date: 2024-09-16 12:22:04.205230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a87876886ac'
down_revision: Union[str, None] = 'b5efd0b4eea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_submissions_form_id', table_name='webhook_submissions')
    op.drop_index('ix_webhook_submissions_id', table_name='webhook_submissions')
    op.drop_table('webhook_submissions')
    op.add_column('api_keys', sa.Column('wordpress_url', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('wordpress_username', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('wordpress_password', sa.String(), nullable=True))
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('api_keys', 'last_used_at')
    op.drop_column('api_keys', 'created_at')
    op.drop_column('api_keys', 'is_active')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('api_keys', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('api_keys', 'wordpress_password')
    op.drop_column('api_keys', 'wordpress_username')
    op.drop_column('api_keys', 'wordpress_url')
    op.create_table('webhook_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brevo_list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brevo_template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('email_structure', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('topic_depth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferred_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='webhook_submissions_pkey')
    )
    op.create_index('ix_webhook_submissions_id', 'webhook_submissions', ['id'], unique=False)
    op.create_index('ix_webhook_submissions_form_id', 'webhook_submissions', ['form_id'], unique=False)
    # ### end Alembic commands ###
