"""Add form_id to sequences table

Revision ID: 59e6ebcfc0cd
Revises: 99c5455a9789
Create Date: 2024-08-30 20:52:57.792720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59e6ebcfc0cd'
down_revision: Union[str, None] = '99c5455a9789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequences', sa.Column('form_id', sa.String(), nullable=True))
    op.add_column('sequences', sa.Column('brevo_list_id', sa.Integer(), nullable=True))
    op.add_column('sequences', sa.Column('total_emails', sa.Integer(), nullable=True))
    op.add_column('sequences', sa.Column('days_between_emails', sa.Integer(), nullable=True))
    op.add_column('sequences', sa.Column('email_structure', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_sequences_form_id'), 'sequences', ['form_id'], unique=False)
    op.create_index(op.f('ix_sequences_recipient_email'), 'sequences', ['recipient_email'], unique=False)
    op.drop_column('sequences', 'updated_at')
    op.drop_column('sequences', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequences', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sequences', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sequences_recipient_email'), table_name='sequences')
    op.drop_index(op.f('ix_sequences_form_id'), table_name='sequences')
    op.drop_column('sequences', 'email_structure')
    op.drop_column('sequences', 'days_between_emails')
    op.drop_column('sequences', 'total_emails')
    op.drop_column('sequences', 'brevo_list_id')
    op.drop_column('sequences', 'form_id')
    # ### end Alembic commands ###
