"""Add sent and sent_at columns to Email model

Revision ID: 6a406b11ae32
Revises: 2a6c31012ba1
Create Date: 2024-08-27 11:23:10.118875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a406b11ae32'
down_revision: Union[str, None] = '2a6c31012ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('sent', sa.Boolean(), nullable=True))
    op.add_column('emails', sa.Column('sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'sent_at')
    op.drop_column('emails', 'sent')
    # ### end Alembic commands ###
