"""Add status, progress, error_message, and next_email_date to Sequence model

Revision ID: 7d90d79554bb
Revises: 7489f6387a0f
Create Date: 2024-08-29 06:16:05.800843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d90d79554bb'
down_revision: Union[str, None] = '7489f6387a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'sent_to_brevo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_email_brevo_message_id', 'emails', type_='unique')
    op.drop_constraint('uq_email_id_sent', 'emails', type_='unique')
    op.drop_constraint('uq_email_sent_to_brevo', 'emails', type_='unique')
    op.drop_column('emails', 'sent')
    op.drop_column('emails', 'sent_at')
    op.add_column('sequences', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sequences', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('sequences', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('sequences', sa.Column('next_email_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequences', 'next_email_date')
    op.drop_column('sequences', 'error_message')
    op.drop_column('sequences', 'progress')
    op.drop_column('sequences', 'status')
    op.add_column('emails', sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('emails', sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_email_sent_to_brevo', 'emails', ['id', 'sent_to_brevo'])
    op.create_unique_constraint('uq_email_id_sent', 'emails', ['id', 'sent'])
    op.create_unique_constraint('uq_email_brevo_message_id', 'emails', ['brevo_message_id'])
    op.alter_column('emails', 'sent_to_brevo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
