"""Add WebhookSubmission model

Revision ID: b5efd0b4eea0
Revises: c141025daceb
Create Date: 2024-09-16 08:00:00.895185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5efd0b4eea0'
down_revision: Union[str, None] = 'c141025daceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('brevo_list_id', sa.Integer(), nullable=True),
    sa.Column('brevo_template_id', sa.Integer(), nullable=True),
    sa.Column('sequence_settings', sa.JSON(), nullable=True),
    sa.Column('email_structure', sa.JSON(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('topic_depth', sa.Integer(), nullable=True),
    sa.Column('preferred_time', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_submissions_form_id'), 'webhook_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_webhook_submissions_id'), 'webhook_submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_submissions_id'), table_name='webhook_submissions')
    op.drop_index(op.f('ix_webhook_submissions_form_id'), table_name='webhook_submissions')
    op.drop_table('webhook_submissions')
    # ### end Alembic commands ###
