"""Add is_active to APIKey

Revision ID: d08c62462b8d
Revises: d7220e393cfb
Create Date: 2024-09-16 18:54:04.762097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08c62462b8d'
down_revision: Union[str, None] = 'd7220e393cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'is_active')
    # ### end Alembic commands ###
