"""Change tags column to JSONB

Revision ID: d57c1c7a4fcd
Revises: d66d100e93cc
Create Date: 2024-09-17 14:45:58.761534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd57c1c7a4fcd'
down_revision: Union[str, None] = 'd66d100e93cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('category', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'tags')
    op.drop_column('emails', 'category')
    # ### end Alembic commands ###
