"""Add reset token fields to User model

Revision ID: d7220e393cfb
Revises: daf85cfcfe6e
Create Date: 2024-09-16 17:27:31.795787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7220e393cfb'
down_revision: Union[str, None] = 'daf85cfcfe6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
